<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" total="1" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="29188" started-at="2019-01-07T20:31:16Z" finished-at="2019-01-07T20:31:46Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="29188" started-at="2019-01-07T20:31:16Z" finished-at="2019-01-07T20:31:46Z">
      <class name="testCases.ValidateErrorTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:testCases.ValidateErrorTest@399f45b1]" name="setUp" is-config="true" duration-ms="12730" started-at="2019-01-08T02:01:16Z" finished-at="2019-01-08T02:01:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="getErrorTest()[pri:0, instance:testCases.ValidateErrorTest@399f45b1]" name="getErrorTest" duration-ms="14352" started-at="2019-01-08T02:01:29Z" finished-at="2019-01-08T02:01:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getErrorTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testCases.ValidateErrorTest@399f45b1]" name="tearDown" is-config="true" duration-ms="2106" started-at="2019-01-08T02:01:44Z" finished-at="2019-01-08T02:01:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testCases.ValidateErrorTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
