<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="A4ML24373" ignored="0" name="Fail Test" tests="2" failures="1" timestamp="25 Dec 2018 12:06:42 GMT" time="0.06" errors="0">
  <testcase name="testCaseOne" time="0.016" classname="com.udemy.rahul.Day1">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.udemy.rahul.Day1.testCaseOne(Day1.java:18)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- testCaseOne -->
  <testcase name="testCaseTwo" time="0.0" classname="com.udemy.rahul.Day1"/>
</testsuite> <!-- Fail Test -->
